services:
  postgres:
    image: postgres:16-alpine
    container_name: igallery-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: igallery
      POSTGRES_PASSWORD: igallery_dev
      POSTGRES_DB: igallery_dp
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U igallery -d igallery_dp']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pg-data:
