// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: agreement_records.sql

package db

import (
	"context"
)

const createAgreementRecord = `-- name: CreateAgreementRecord :one
INSERT INTO agreement_records (id, user_id, terms_version, privacy_accepted, marketing_accepted)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, terms_version, privacy_accepted, marketing_accepted, accepted_at
`

type CreateAgreementRecordParams struct {
	ID                string `json:"id"`
	UserID            string `json:"user_id"`
	TermsVersion      string `json:"terms_version"`
	PrivacyAccepted   bool   `json:"privacy_accepted"`
	MarketingAccepted bool   `json:"marketing_accepted"`
}

func (q *Queries) CreateAgreementRecord(ctx context.Context, arg CreateAgreementRecordParams) (AgreementRecord, error) {
	row := q.db.QueryRow(ctx, createAgreementRecord,
		arg.ID,
		arg.UserID,
		arg.TermsVersion,
		arg.PrivacyAccepted,
		arg.MarketingAccepted,
	)
	var i AgreementRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TermsVersion,
		&i.PrivacyAccepted,
		&i.MarketingAccepted,
		&i.AcceptedAt,
	)
	return i, err
}
