// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: awards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAward = `-- name: CreateAward :one
INSERT INTO awards (id, drawing_id, child_profile_id, event_id, rank)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, drawing_id, child_profile_id, event_id, rank, awarded_at
`

type CreateAwardParams struct {
	ID             string  `json:"id"`
	DrawingID      string  `json:"drawing_id"`
	ChildProfileID string  `json:"child_profile_id"`
	EventID        *string `json:"event_id"`
	Rank           string  `json:"rank"`
}

// 향후 R13 모더레이션 승인 후 호출. R9 단계엔 dev seed 용으로도 쓰임.
func (q *Queries) CreateAward(ctx context.Context, arg CreateAwardParams) (Award, error) {
	row := q.db.QueryRow(ctx, createAward,
		arg.ID,
		arg.DrawingID,
		arg.ChildProfileID,
		arg.EventID,
		arg.Rank,
	)
	var i Award
	err := row.Scan(
		&i.ID,
		&i.DrawingID,
		&i.ChildProfileID,
		&i.EventID,
		&i.Rank,
		&i.AwardedAt,
	)
	return i, err
}

const listAwardsByChild = `-- name: ListAwardsByChild :many
SELECT
    a.id              AS award_id,
    a.rank            AS rank,
    a.event_id        AS event_id,
    a.awarded_at      AS awarded_at,
    d.id              AS drawing_id,
    d.mode            AS mode,
    d.title           AS title,
    d.thumbnail_url   AS thumbnail_url,
    d.image_url       AS image_url,
    d.timelapse_url   AS timelapse_url,
    d.is_public       AS is_public,
    d.completed_at    AS completed_at
FROM awards a
JOIN drawings d        ON d.id = a.drawing_id
JOIN child_profiles c  ON c.id = a.child_profile_id
WHERE a.child_profile_id = $1
    AND c.user_id = $2
    AND d.deleted_at IS NULL
    AND c.deleted_at IS NULL
ORDER BY a.awarded_at DESC
LIMIT  $4::int
OFFSET $3::int
`

type ListAwardsByChildParams struct {
	ChildProfileID string `json:"child_profile_id"`
	UserID         string `json:"user_id"`
	Off            int32  `json:"off"`
	Lim            int32  `json:"lim"`
}

type ListAwardsByChildRow struct {
	AwardID      string             `json:"award_id"`
	Rank         string             `json:"rank"`
	EventID      *string            `json:"event_id"`
	AwardedAt    pgtype.Timestamptz `json:"awarded_at"`
	DrawingID    string             `json:"drawing_id"`
	Mode         string             `json:"mode"`
	Title        string             `json:"title"`
	ThumbnailUrl *string            `json:"thumbnail_url"`
	ImageUrl     *string            `json:"image_url"`
	TimelapseUrl *string            `json:"timelapse_url"`
	IsPublic     bool               `json:"is_public"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

// 수상작 탭. award + drawing 필드 조인.
func (q *Queries) ListAwardsByChild(ctx context.Context, arg ListAwardsByChildParams) ([]ListAwardsByChildRow, error) {
	rows, err := q.db.Query(ctx, listAwardsByChild,
		arg.ChildProfileID,
		arg.UserID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAwardsByChildRow
	for rows.Next() {
		var i ListAwardsByChildRow
		if err := rows.Scan(
			&i.AwardID,
			&i.Rank,
			&i.EventID,
			&i.AwardedAt,
			&i.DrawingID,
			&i.Mode,
			&i.Title,
			&i.ThumbnailUrl,
			&i.ImageUrl,
			&i.TimelapseUrl,
			&i.IsPublic,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
