// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: child_profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveChildProfilesByUser = `-- name: CountActiveChildProfilesByUser :one
SELECT COUNT(*)::int AS count
FROM child_profiles
WHERE user_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) CountActiveChildProfilesByUser(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveChildProfilesByUser, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createChildProfile = `-- name: CreateChildProfile :one
INSERT INTO child_profiles (id, user_id, name, birth_date, profile_emoji, drawing_level)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, birth_date, profile_emoji, drawing_level, created_at, updated_at, deleted_at
`

type CreateChildProfileParams struct {
	ID           string      `json:"id"`
	UserID       string      `json:"user_id"`
	Name         string      `json:"name"`
	BirthDate    pgtype.Date `json:"birth_date"`
	ProfileEmoji string      `json:"profile_emoji"`
	DrawingLevel string      `json:"drawing_level"`
}

func (q *Queries) CreateChildProfile(ctx context.Context, arg CreateChildProfileParams) (ChildProfile, error) {
	row := q.db.QueryRow(ctx, createChildProfile,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.BirthDate,
		arg.ProfileEmoji,
		arg.DrawingLevel,
	)
	var i ChildProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BirthDate,
		&i.ProfileEmoji,
		&i.DrawingLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChildProfile = `-- name: GetChildProfile :one
SELECT id, user_id, name, birth_date, profile_emoji, drawing_level, created_at, updated_at, deleted_at
FROM child_profiles
WHERE id = $1
    AND user_id = $2
    AND deleted_at IS NULL
`

type GetChildProfileParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetChildProfile(ctx context.Context, arg GetChildProfileParams) (ChildProfile, error) {
	row := q.db.QueryRow(ctx, getChildProfile, arg.ID, arg.UserID)
	var i ChildProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BirthDate,
		&i.ProfileEmoji,
		&i.DrawingLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listChildProfilesByUser = `-- name: ListChildProfilesByUser :many
SELECT id, user_id, name, birth_date, profile_emoji, drawing_level, created_at, updated_at, deleted_at
FROM child_profiles
WHERE user_id = $1
    AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListChildProfilesByUser(ctx context.Context, userID string) ([]ChildProfile, error) {
	rows, err := q.db.Query(ctx, listChildProfilesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChildProfile
	for rows.Next() {
		var i ChildProfile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.BirthDate,
			&i.ProfileEmoji,
			&i.DrawingLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteChildProfile = `-- name: SoftDeleteChildProfile :exec
UPDATE child_profiles
SET deleted_at = NOW()
WHERE id = $1
    AND user_id = $2
    AND deleted_at IS NULL
`

type SoftDeleteChildProfileParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SoftDeleteChildProfile(ctx context.Context, arg SoftDeleteChildProfileParams) error {
	_, err := q.db.Exec(ctx, softDeleteChildProfile, arg.ID, arg.UserID)
	return err
}

const updateChildProfile = `-- name: UpdateChildProfile :one
UPDATE child_profiles
SET
    name          = COALESCE($1,          name),
    birth_date    = COALESCE($2,    birth_date),
    profile_emoji = COALESCE($3, profile_emoji),
    drawing_level = COALESCE($4, drawing_level)
WHERE id = $5
    AND user_id = $6
    AND deleted_at IS NULL
RETURNING id, user_id, name, birth_date, profile_emoji, drawing_level, created_at, updated_at, deleted_at
`

type UpdateChildProfileParams struct {
	Name         *string     `json:"name"`
	BirthDate    pgtype.Date `json:"birth_date"`
	ProfileEmoji *string     `json:"profile_emoji"`
	DrawingLevel *string     `json:"drawing_level"`
	ID           string      `json:"id"`
	UserID       string      `json:"user_id"`
}

func (q *Queries) UpdateChildProfile(ctx context.Context, arg UpdateChildProfileParams) (ChildProfile, error) {
	row := q.db.QueryRow(ctx, updateChildProfile,
		arg.Name,
		arg.BirthDate,
		arg.ProfileEmoji,
		arg.DrawingLevel,
		arg.ID,
		arg.UserID,
	)
	var i ChildProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BirthDate,
		&i.ProfileEmoji,
		&i.DrawingLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
