// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: coin_ledgers.sql

package db

import (
	"context"
)

const insertCoinLedger = `-- name: InsertCoinLedger :exec
INSERT INTO coin_ledgers (id, user_id, delta, reason, balance_after, ref_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCoinLedgerParams struct {
	ID           string  `json:"id"`
	UserID       string  `json:"user_id"`
	Delta        int32   `json:"delta"`
	Reason       string  `json:"reason"`
	BalanceAfter int32   `json:"balance_after"`
	RefID        *string `json:"ref_id"`
}

func (q *Queries) InsertCoinLedger(ctx context.Context, arg InsertCoinLedgerParams) error {
	_, err := q.db.Exec(ctx, insertCoinLedger,
		arg.ID,
		arg.UserID,
		arg.Delta,
		arg.Reason,
		arg.BalanceAfter,
		arg.RefID,
	)
	return err
}

const listCoinLedgersByUser = `-- name: ListCoinLedgersByUser :many
SELECT id, user_id, delta, reason, balance_after, ref_id, created_at FROM coin_ledgers
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCoinLedgersByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListCoinLedgersByUser(ctx context.Context, arg ListCoinLedgersByUserParams) ([]CoinLedger, error) {
	rows, err := q.db.Query(ctx, listCoinLedgersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoinLedger
	for rows.Next() {
		var i CoinLedger
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Delta,
			&i.Reason,
			&i.BalanceAfter,
			&i.RefID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
