// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: notifications.sql

package db

import (
	"context"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id, user_id, category, title, description, icon, cta)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, category, title, description, icon, cta, read_status, created_at
`

type CreateNotificationParams struct {
	ID          string  `json:"id"`
	UserID      string  `json:"user_id"`
	Category    string  `json:"category"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Icon        *string `json:"icon"`
	Cta         *string `json:"cta"`
}

// dev seed / 시스템 트리거 (R12 결제, R13 수상 등에서 호출 예정).
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Category,
		arg.Title,
		arg.Description,
		arg.Icon,
		arg.Cta,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.Cta,
		&i.ReadStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*)::int AS count
FROM notifications
WHERE user_id = $1 AND read_status = 'unRead'
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, getUnreadNotificationCount, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, category, title, description, icon, cta, read_status, created_at
FROM notifications
WHERE user_id = $1
    AND ($2::text IS NULL OR category = $2::text)
ORDER BY created_at DESC
LIMIT  $4::int
OFFSET $3::int
`

type ListNotificationsByUserParams struct {
	UserID   string  `json:"user_id"`
	Category *string `json:"category"`
	Off      int32   `json:"off"`
	Lim      int32   `json:"lim"`
}

// category 가 NULL 이면 전체. 최근순.
func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser,
		arg.UserID,
		arg.Category,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.Icon,
			&i.Cta,
			&i.ReadStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_status = 'read'
WHERE user_id = $1 AND read_status = 'unRead'
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read_status = 'read'
WHERE id = $1 AND user_id = $2 AND read_status = 'unRead'
`

type MarkNotificationReadParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}
