// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: token_issuance_log.sql

package db

import (
	"context"
)

const insertTokenIssuanceLog = `-- name: InsertTokenIssuanceLog :exec
INSERT INTO token_issuance_log (id, user_id, event, access_jti, refresh_id, user_agent, ip_address)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertTokenIssuanceLogParams struct {
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
	Event     string  `json:"event"`
	AccessJti *string `json:"access_jti"`
	RefreshID *string `json:"refresh_id"`
	UserAgent *string `json:"user_agent"`
	IpAddress *string `json:"ip_address"`
}

func (q *Queries) InsertTokenIssuanceLog(ctx context.Context, arg InsertTokenIssuanceLogParams) error {
	_, err := q.db.Exec(ctx, insertTokenIssuanceLog,
		arg.ID,
		arg.UserID,
		arg.Event,
		arg.AccessJti,
		arg.RefreshID,
		arg.UserAgent,
		arg.IpAddress,
	)
	return err
}
