// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: coin_wallets.sql

package db

import (
	"context"
)

const createCoinWallet = `-- name: CreateCoinWallet :one
INSERT INTO coin_wallets (user_id)
VALUES ($1)
RETURNING user_id, holding_coins, monthly_coin_allowance, daily_topup_remaining_days, updated_at
`

func (q *Queries) CreateCoinWallet(ctx context.Context, userID string) (CoinWallet, error) {
	row := q.db.QueryRow(ctx, createCoinWallet, userID)
	var i CoinWallet
	err := row.Scan(
		&i.UserID,
		&i.HoldingCoins,
		&i.MonthlyCoinAllowance,
		&i.DailyTopupRemainingDays,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoinWallet = `-- name: GetCoinWallet :one
SELECT user_id, holding_coins, monthly_coin_allowance, daily_topup_remaining_days, updated_at FROM coin_wallets
WHERE user_id = $1
`

func (q *Queries) GetCoinWallet(ctx context.Context, userID string) (CoinWallet, error) {
	row := q.db.QueryRow(ctx, getCoinWallet, userID)
	var i CoinWallet
	err := row.Scan(
		&i.UserID,
		&i.HoldingCoins,
		&i.MonthlyCoinAllowance,
		&i.DailyTopupRemainingDays,
		&i.UpdatedAt,
	)
	return i, err
}
