// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: drawings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDrawing = `-- name: CreateDrawing :one
INSERT INTO drawings (
    id, child_profile_id, mode, title,
    thumbnail_url, image_url, timelapse_url,
    is_public, status, completed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, child_profile_id, mode, title, thumbnail_url, image_url, timelapse_url, is_public, status, started_at, completed_at, created_at, updated_at, deleted_at
`

type CreateDrawingParams struct {
	ID             string             `json:"id"`
	ChildProfileID string             `json:"child_profile_id"`
	Mode           string             `json:"mode"`
	Title          string             `json:"title"`
	ThumbnailUrl   *string            `json:"thumbnail_url"`
	ImageUrl       *string            `json:"image_url"`
	TimelapseUrl   *string            `json:"timelapse_url"`
	IsPublic       bool               `json:"is_public"`
	Status         string             `json:"status"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateDrawing(ctx context.Context, arg CreateDrawingParams) (Drawing, error) {
	row := q.db.QueryRow(ctx, createDrawing,
		arg.ID,
		arg.ChildProfileID,
		arg.Mode,
		arg.Title,
		arg.ThumbnailUrl,
		arg.ImageUrl,
		arg.TimelapseUrl,
		arg.IsPublic,
		arg.Status,
		arg.CompletedAt,
	)
	var i Drawing
	err := row.Scan(
		&i.ID,
		&i.ChildProfileID,
		&i.Mode,
		&i.Title,
		&i.ThumbnailUrl,
		&i.ImageUrl,
		&i.TimelapseUrl,
		&i.IsPublic,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDrawing = `-- name: GetDrawing :one
SELECT d.id, d.child_profile_id, d.mode, d.title, d.thumbnail_url, d.image_url, d.timelapse_url, d.is_public, d.status, d.started_at, d.completed_at, d.created_at, d.updated_at, d.deleted_at
FROM drawings d
JOIN child_profiles c ON c.id = d.child_profile_id
WHERE d.id = $1
    AND c.user_id = $2
    AND d.deleted_at IS NULL
    AND c.deleted_at IS NULL
`

type GetDrawingParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

// 단건 조회 + 소유권(자녀의 부모 == 요청 유저) 검증.
func (q *Queries) GetDrawing(ctx context.Context, arg GetDrawingParams) (Drawing, error) {
	row := q.db.QueryRow(ctx, getDrawing, arg.ID, arg.UserID)
	var i Drawing
	err := row.Scan(
		&i.ID,
		&i.ChildProfileID,
		&i.Mode,
		&i.Title,
		&i.ThumbnailUrl,
		&i.ImageUrl,
		&i.TimelapseUrl,
		&i.IsPublic,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDrawingsByChild = `-- name: ListDrawingsByChild :many
SELECT d.id, d.child_profile_id, d.mode, d.title, d.thumbnail_url, d.image_url, d.timelapse_url, d.is_public, d.status, d.started_at, d.completed_at, d.created_at, d.updated_at, d.deleted_at
FROM drawings d
JOIN child_profiles c ON c.id = d.child_profile_id
WHERE d.child_profile_id = $1
    AND c.user_id = $2
    AND d.deleted_at IS NULL
    AND c.deleted_at IS NULL
    AND ($3::text IS NULL OR d.status = $3::text)
    AND ($4::boolean IS NULL
         OR $4::boolean = FALSE
         OR (d.is_public = TRUE AND d.status = 'completed'))
    AND ($5::timestamptz IS NULL
         OR d.created_at >= $5::timestamptz)
    AND ($6::timestamptz IS NULL
         OR d.created_at <  $6::timestamptz)
ORDER BY d.created_at DESC
LIMIT  $8::int
OFFSET $7::int
`

type ListDrawingsByChildParams struct {
	ChildProfileID string             `json:"child_profile_id"`
	UserID         string             `json:"user_id"`
	Status         *string            `json:"status"`
	OnlyPublic     *bool              `json:"only_public"`
	MonthStart     pgtype.Timestamptz `json:"month_start"`
	MonthEnd       pgtype.Timestamptz `json:"month_end"`
	Off            int32              `json:"off"`
	Lim            int32              `json:"lim"`
}

// 마이갤러리 보관함/공개작품 통합 쿼리.
// status / visibility / month 필터는 nullable 인자로 단일 쿼리 처리.
// month 는 'YYYY-MM' 형식. NULL 이면 전체 기간.
func (q *Queries) ListDrawingsByChild(ctx context.Context, arg ListDrawingsByChildParams) ([]Drawing, error) {
	rows, err := q.db.Query(ctx, listDrawingsByChild,
		arg.ChildProfileID,
		arg.UserID,
		arg.Status,
		arg.OnlyPublic,
		arg.MonthStart,
		arg.MonthEnd,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drawing
	for rows.Next() {
		var i Drawing
		if err := rows.Scan(
			&i.ID,
			&i.ChildProfileID,
			&i.Mode,
			&i.Title,
			&i.ThumbnailUrl,
			&i.ImageUrl,
			&i.TimelapseUrl,
			&i.IsPublic,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDrawing = `-- name: SoftDeleteDrawing :exec
UPDATE drawings d
SET deleted_at = NOW()
WHERE d.id = $1
    AND d.child_profile_id IN (
        SELECT c.id FROM child_profiles c
        WHERE c.user_id = $2 AND c.deleted_at IS NULL
    )
    AND d.deleted_at IS NULL
`

type SoftDeleteDrawingParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SoftDeleteDrawing(ctx context.Context, arg SoftDeleteDrawingParams) error {
	_, err := q.db.Exec(ctx, softDeleteDrawing, arg.ID, arg.UserID)
	return err
}

const updateDrawing = `-- name: UpdateDrawing :one
UPDATE drawings d
SET
    title         = COALESCE($1,         d.title),
    is_public     = COALESCE($2,     d.is_public),
    status        = COALESCE($3,        d.status),
    completed_at  = COALESCE($4,  d.completed_at)
WHERE d.id = $5
    AND d.child_profile_id IN (
        SELECT c.id FROM child_profiles c
        WHERE c.user_id = $6 AND c.deleted_at IS NULL
    )
    AND d.deleted_at IS NULL
RETURNING d.id, d.child_profile_id, d.mode, d.title, d.thumbnail_url, d.image_url, d.timelapse_url, d.is_public, d.status, d.started_at, d.completed_at, d.created_at, d.updated_at, d.deleted_at
`

type UpdateDrawingParams struct {
	Title       *string            `json:"title"`
	IsPublic    *bool              `json:"is_public"`
	Status      *string            `json:"status"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
}

// 부분 갱신 (title / is_public / status / completed_at). 각 필드는 NULL 이면 미변경.
// status='completed' 로 전이될 때 completed_at 도 같이 채워야 CHECK 통과.
func (q *Queries) UpdateDrawing(ctx context.Context, arg UpdateDrawingParams) (Drawing, error) {
	row := q.db.QueryRow(ctx, updateDrawing,
		arg.Title,
		arg.IsPublic,
		arg.Status,
		arg.CompletedAt,
		arg.ID,
		arg.UserID,
	)
	var i Drawing
	err := row.Scan(
		&i.ID,
		&i.ChildProfileID,
		&i.Mode,
		&i.Title,
		&i.ThumbnailUrl,
		&i.ImageUrl,
		&i.TimelapseUrl,
		&i.IsPublic,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
