// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AgreementRecord struct {
	ID                string             `json:"id"`
	UserID            string             `json:"user_id"`
	TermsVersion      string             `json:"terms_version"`
	PrivacyAccepted   bool               `json:"privacy_accepted"`
	MarketingAccepted bool               `json:"marketing_accepted"`
	AcceptedAt        pgtype.Timestamptz `json:"accepted_at"`
}

type ChildProfile struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	Name         string             `json:"name"`
	BirthDate    pgtype.Date        `json:"birth_date"`
	ProfileEmoji string             `json:"profile_emoji"`
	DrawingLevel string             `json:"drawing_level"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type CoinLedger struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	Delta        int32              `json:"delta"`
	Reason       string             `json:"reason"`
	BalanceAfter int32              `json:"balance_after"`
	RefID        *string            `json:"ref_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CoinWallet struct {
	UserID                  string             `json:"user_id"`
	HoldingCoins            int32              `json:"holding_coins"`
	MonthlyCoinAllowance    int32              `json:"monthly_coin_allowance"`
	DailyTopupRemainingDays int16              `json:"daily_topup_remaining_days"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID               string             `json:"id"`
	Title            string             `json:"title"`
	Subtitle         *string            `json:"subtitle"`
	ImageUrl         *string            `json:"image_url"`
	StartAt          pgtype.Timestamptz `json:"start_at"`
	EndAt            pgtype.Timestamptz `json:"end_at"`
	Status           string             `json:"status"`
	ParticipantCount int32              `json:"participant_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type EventParticipation struct {
	ID             string             `json:"id"`
	EventID        string             `json:"event_id"`
	ChildProfileID string             `json:"child_profile_id"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
}

type IdentityVerification struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	Provider   string             `json:"provider"`
	Status     string             `json:"status"`
	CiHash     *string            `json:"ci_hash"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Category    string             `json:"category"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Icon        *string            `json:"icon"`
	Cta         *string            `json:"cta"`
	ReadStatus  string             `json:"read_status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type OauthAccount struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	Email          *string            `json:"email"`
	LinkedAt       pgtype.Timestamptz `json:"linked_at"`
}

type Subscription struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	Plan       string             `json:"plan"`
	Status     string             `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	EndsAt     pgtype.Timestamptz `json:"ends_at"`
	CanceledAt pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SupportInquiry struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Subject   string             `json:"subject"`
	Message   string             `json:"message"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	CreatedAt      time.Time          `json:"created_at"`
	Email          *string            `json:"email"`
	PasswordHash   *string            `json:"password_hash"`
	Description    *string            `json:"description"`
	Avatar         *string            `json:"avatar"`
	Locale         string             `json:"locale"`
	Country        string             `json:"country"`
	MarketingOptIn bool               `json:"marketing_opt_in"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type UserPreference struct {
	UserID         string             `json:"user_id"`
	NotifDrawing   bool               `json:"notif_drawing"`
	NotifEvent     bool               `json:"notif_event"`
	NotifSystem    bool               `json:"notif_system"`
	NotifMarketing bool               `json:"notif_marketing"`
	DndEnabled     bool               `json:"dnd_enabled"`
	DndStart       string             `json:"dnd_start"`
	DndEnd         string             `json:"dnd_end"`
	SafeMode       bool               `json:"safe_mode"`
	PaymentLock    bool               `json:"payment_lock"`
	TogetherChat   bool               `json:"together_chat"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type WithdrawalRequest struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Mode        string             `json:"mode"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	CanceledAt  pgtype.Timestamptz `json:"canceled_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}
