// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: push_tokens.sql

package db

import (
	"context"
)

const deletePushToken = `-- name: DeletePushToken :exec
DELETE FROM push_tokens
WHERE user_id = $1 AND token = $2
`

type DeletePushTokenParams struct {
	UserID string `json:"user_id"`
	Token  string `json:"token"`
}

func (q *Queries) DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error {
	_, err := q.db.Exec(ctx, deletePushToken, arg.UserID, arg.Token)
	return err
}

const upsertPushToken = `-- name: UpsertPushToken :one
INSERT INTO push_tokens (id, user_id, platform, token)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, token)
DO UPDATE SET last_seen_at = NOW()
RETURNING id, user_id, platform, token, created_at, last_seen_at
`

type UpsertPushTokenParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	Platform string `json:"platform"`
	Token    string `json:"token"`
}

// 같은 user+token 이 들어오면 last_seen_at 만 갱신 (재로그인/앱 재실행 시 호출).
func (q *Queries) UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) (PushToken, error) {
	row := q.db.QueryRow(ctx, upsertPushToken,
		arg.ID,
		arg.UserID,
		arg.Platform,
		arg.Token,
	)
	var i PushToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Token,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
