// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: support_inquiries.sql

package db

import (
	"context"
)

const createSupportInquiry = `-- name: CreateSupportInquiry :one
INSERT INTO support_inquiries (id, user_id, subject, message)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, subject, message, status, created_at
`

type CreateSupportInquiryParams struct {
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
	Subject string `json:"subject"`
	Message string `json:"message"`
}

func (q *Queries) CreateSupportInquiry(ctx context.Context, arg CreateSupportInquiryParams) (SupportInquiry, error) {
	row := q.db.QueryRow(ctx, createSupportInquiry,
		arg.ID,
		arg.UserID,
		arg.Subject,
		arg.Message,
	)
	var i SupportInquiry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
