// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: user_preferences.sql

package db

import (
	"context"
)

const createUserPreferences = `-- name: CreateUserPreferences :one
INSERT INTO user_preferences (user_id)
VALUES ($1)
RETURNING user_id, notif_drawing, notif_event, notif_system, notif_marketing, dnd_enabled, dnd_start, dnd_end, safe_mode, payment_lock, together_chat, updated_at
`

func (q *Queries) CreateUserPreferences(ctx context.Context, userID string) (UserPreference, error) {
	row := q.db.QueryRow(ctx, createUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.NotifDrawing,
		&i.NotifEvent,
		&i.NotifSystem,
		&i.NotifMarketing,
		&i.DndEnabled,
		&i.DndStart,
		&i.DndEnd,
		&i.SafeMode,
		&i.PaymentLock,
		&i.TogetherChat,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, notif_drawing, notif_event, notif_system, notif_marketing, dnd_enabled, dnd_start, dnd_end, safe_mode, payment_lock, together_chat, updated_at FROM user_preferences
WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID string) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.NotifDrawing,
		&i.NotifEvent,
		&i.NotifSystem,
		&i.NotifMarketing,
		&i.DndEnabled,
		&i.DndStart,
		&i.DndEnd,
		&i.SafeMode,
		&i.PaymentLock,
		&i.TogetherChat,
		&i.UpdatedAt,
	)
	return i, err
}

const patchUserPreferences = `-- name: PatchUserPreferences :one
UPDATE user_preferences
SET
    notif_drawing   = COALESCE($2,   notif_drawing),
    notif_event     = COALESCE($3,     notif_event),
    notif_system    = COALESCE($4,    notif_system),
    notif_marketing = COALESCE($5, notif_marketing),
    dnd_enabled     = COALESCE($6,     dnd_enabled),
    dnd_start       = COALESCE($7,       dnd_start),
    dnd_end         = COALESCE($8,         dnd_end),
    safe_mode       = COALESCE($9,       safe_mode),
    payment_lock    = COALESCE($10,    payment_lock),
    together_chat   = COALESCE($11,   together_chat)
  WHERE user_id = $1
  RETURNING user_id, notif_drawing, notif_event, notif_system, notif_marketing, dnd_enabled, dnd_start, dnd_end, safe_mode, payment_lock, together_chat, updated_at
`

type PatchUserPreferencesParams struct {
	UserID         string  `json:"user_id"`
	NotifDrawing   *bool   `json:"notif_drawing"`
	NotifEvent     *bool   `json:"notif_event"`
	NotifSystem    *bool   `json:"notif_system"`
	NotifMarketing *bool   `json:"notif_marketing"`
	DndEnabled     *bool   `json:"dnd_enabled"`
	DndStart       *string `json:"dnd_start"`
	DndEnd         *string `json:"dnd_end"`
	SafeMode       *bool   `json:"safe_mode"`
	PaymentLock    *bool   `json:"payment_lock"`
	TogetherChat   *bool   `json:"together_chat"`
}

func (q *Queries) PatchUserPreferences(ctx context.Context, arg PatchUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, patchUserPreferences,
		arg.UserID,
		arg.NotifDrawing,
		arg.NotifEvent,
		arg.NotifSystem,
		arg.NotifMarketing,
		arg.DndEnabled,
		arg.DndStart,
		arg.DndEnd,
		arg.SafeMode,
		arg.PaymentLock,
		arg.TogetherChat,
	)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.NotifDrawing,
		&i.NotifEvent,
		&i.NotifSystem,
		&i.NotifMarketing,
		&i.DndEnabled,
		&i.DndStart,
		&i.DndEnd,
		&i.SafeMode,
		&i.PaymentLock,
		&i.TogetherChat,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE user_preferences
SET
    notif_drawing   = $2,
    notif_event     = $3,
    notif_system    = $4,
    notif_marketing = $5,
    dnd_enabled     = $6,
    dnd_start       = $7,
    dnd_end         = $8,
    safe_mode       = $9,
    payment_lock    = $10,
    together_chat   = $11
  WHERE user_id = $1
  RETURNING user_id, notif_drawing, notif_event, notif_system, notif_marketing, dnd_enabled, dnd_start, dnd_end, safe_mode, payment_lock, together_chat, updated_at
`

type UpdateUserPreferencesParams struct {
	UserID         string `json:"user_id"`
	NotifDrawing   bool   `json:"notif_drawing"`
	NotifEvent     bool   `json:"notif_event"`
	NotifSystem    bool   `json:"notif_system"`
	NotifMarketing bool   `json:"notif_marketing"`
	DndEnabled     bool   `json:"dnd_enabled"`
	DndStart       string `json:"dnd_start"`
	DndEnd         string `json:"dnd_end"`
	SafeMode       bool   `json:"safe_mode"`
	PaymentLock    bool   `json:"payment_lock"`
	TogetherChat   bool   `json:"together_chat"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, updateUserPreferences,
		arg.UserID,
		arg.NotifDrawing,
		arg.NotifEvent,
		arg.NotifSystem,
		arg.NotifMarketing,
		arg.DndEnabled,
		arg.DndStart,
		arg.DndEnd,
		arg.SafeMode,
		arg.PaymentLock,
		arg.TogetherChat,
	)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.NotifDrawing,
		&i.NotifEvent,
		&i.NotifSystem,
		&i.NotifMarketing,
		&i.DndEnabled,
		&i.DndStart,
		&i.DndEnd,
		&i.SafeMode,
		&i.PaymentLock,
		&i.TogetherChat,
		&i.UpdatedAt,
	)
	return i, err
}
