// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: user_preferences.sql

package db

import (
	"context"
)

const createUserPreferences = `-- name: CreateUserPreferences :one
INSERT INTO user_preferences (user_id)
VALUES ($1)
RETURNING user_id, notif_drawing, notif_event, notif_system, notif_marketing, dnd_enabled, dnd_start, dnd_end, safe_mode, payment_lock, together_chat, updated_at
`

func (q *Queries) CreateUserPreferences(ctx context.Context, userID string) (UserPreference, error) {
	row := q.db.QueryRow(ctx, createUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.NotifDrawing,
		&i.NotifEvent,
		&i.NotifSystem,
		&i.NotifMarketing,
		&i.DndEnabled,
		&i.DndStart,
		&i.DndEnd,
		&i.SafeMode,
		&i.PaymentLock,
		&i.TogetherChat,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, notif_drawing, notif_event, notif_system, notif_marketing, dnd_enabled, dnd_start, dnd_end, safe_mode, payment_lock, together_chat, updated_at FROM user_preferences
WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID string) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.NotifDrawing,
		&i.NotifEvent,
		&i.NotifSystem,
		&i.NotifMarketing,
		&i.DndEnabled,
		&i.DndStart,
		&i.DndEnd,
		&i.SafeMode,
		&i.PaymentLock,
		&i.TogetherChat,
		&i.UpdatedAt,
	)
	return i, err
}
